#include "CFG_Reader.h"




Graph CFG_Reader::get_cfg_graph()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:000000000000096A begin
{
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:000000000000096A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void CFG_Reader::generate_cfg(void  path)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:000000000000099A begin
{
    
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:000000000000099A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
