#include "First_gen.h"




string First_gen::get_first(void  name)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:0000000000000995 begin
{
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:0000000000000995 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void First_gen::generate_first()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:0000000000000998 begin
{
    
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:0000000000000998 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
