#include "Follow_gen.h"




string Follow_gen::get_follow(void  name)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:000000000000098A begin
{
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:000000000000098A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Follow_gen::generate_follow()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:0000000000000990 begin
{
    
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:0000000000000990 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
