#include "Graph.h"




void Graph::add_child(void  name)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:0000000000000976 begin
{
    
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:0000000000000976 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

string Graph::get_child(void  name)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:000000000000097E begin
{
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:000000000000097E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
