#include "Pharsing_Table_Gen.h"




void Pharsing_Table_Gen::Parsing_Table_Gen(void  first, void  follow, void  terminals, void  nonTerminals)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:00000000000009AD begin
{
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:00000000000009AD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Array[][] Pharsing_Table_Gen::get_parsing_table()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:00000000000009AF begin
{
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:00000000000009AF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
