#include "Validator.h"




void Validator::Validator(void  parsingtable, void  terminals, void  nonTerminals)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:00000000000009BA begin
{
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:00000000000009BA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

vector<string> Validator::get_derivations(void  tokens)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:00000000000009BF begin
{
}
// section -64--88--69-1--16c8dc3d:145faf1e0c2:-8000:00000000000009BF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
